- name: BlueTeam_Initial_Setup
  hosts: blueteam
  tasks:
    block:
      - name: Add Wireshark Repository
        ansible.builtin.apt_repository:
          repo: ppa:wireshark-dev/stable
      - name: Update Repositories # Will this work on its own? Possibly!
        ansible.builtin.apt:
          update_cache: yes
      - name: Install Sniffers
        ansible.builtin.apt:
          name: 
          - wireshark
          - tcpdump
      - name: Install Nginx
        ansible.builtin.apt:
          name: nginx
        notify:
          - Stop Nginx
      - name: Install XRDP
        ansible.builtin.apt:
          name: xrdp
        notify:
          - Restart rdp
#          - Configure rdp
      - name: Install Telnet
        ansible.builtin.apt:
          name: telnetd
        notify:
          - Start telnet
      - name: user_create
        ansible.builtin.shell: |
          sudo useradd -m worker 
          sudo useradd -m manager -G sudo
          chpass "worker:ThisIsAGreatPassword" 
          chpass "manager:WellThisIsGood"
      - name: Docker
        ansible.builtin.apt:
          name: docker.io
        notify:
          - Docker Config
          - Docker network
          - Web container
          - Pull proxy
          - User Config


handlers:
  - name: Stop Nginx
    ansible.builtin.systemd:
      name: nginx
      state: stopped
#  - name: Configure rdp
#    ansible.builtin.shell: 
#      cmd: # Add desktop type to user homes.
#    notify:
#      - Restart rdp
  # Restart the rdp service 
  - name: Restart rdp
    ansible.builtin.systemd:
      name: xrdp
      state: restarted
  # Start the Telnet server 
  - name: Start telnet
    ansible.builtin.systemd:
      name: inetd
      state: started
  # Create the docker network 
  - name: Docker network
    community.docker.docker_network:
      name: website_proxy_network
  # Create and start the web container (running on 
  - name: Web container
    community.docker.docker_container:
      image: nginx # Change to be site once container is uploaded
      name: web-site
      pull: true
      state: started
      published_ports:
        - "8080:80"
  - name: Pull proxy
    community.docker.docker_image:
      name: nginx # Pull image for the proxy
      source: pull
      # Select platform for pulling. If not specified, will pull whatever docker prefers.
  - name: User Config
    ansible.builtin.shell: | 
      usermod -aG manager docker
    



